-- ----------------------
-- Data base exploration
-- ----------------------

-- Explore all objects in database
select * from information_schema.tables;

-- Explore all columns in database
select * from information_schema.columns;

-- Explore all countries our customers come from
select distinct country from golddim_customers;

-- ----------------------
-- Dimension exploration
-- ----------------------

-- Explore all categories "The Major Divisions"
select distinct category, subcategory, product_name from golddim_products
order by 1, 2, 3;

-- ----------------------
-- Date exploration
-- ----------------------

-- Date of the first and last order
select min(order_date) as first_order_date, 
		max(order_date) as last_order_date,
        timestampdiff(YEAR, min(order_date), max(order_date)) as order_range_years
from goldfact_sales
where order_date != "";

-- Youngest and the oldest customer
select
min(birthdate) as oldest_customer,
timestampdiff(year, min(birthdate), curdate()) as oldest_age,
max(birthdate) as youngest_customer,
timestampdiff(year, max(birthdate), curdate()) as youngest_age
from golddim_customers
where birthdate != "";

-- ----------------------
-- Measure exploration
-- ----------------------

-- Total Sales
Select
sum(sales_amount) as Total_Sales
from goldfact_sales;

-- Total items sold
Select
sum(quantity) as Total_quantity
from goldfact_sales;

-- Average selling price
Select
avg(price) as Avg_price
from goldfact_sales;

-- Total number of Orders
Select
count(order_number) as Total_orders
from goldfact_sales;

Select
count(distinct order_number) as Total_orders
from goldfact_sales;

-- Total number of products
Select
count(product_id) as Total_product
from golddim_products;

-- Total number of customers
Select
count(customer_key) as Total_customer
from golddim_customers;

-- Total number of customers that has placed an order
Select
count(distinct customer_key) as Total_customer
from goldfact_sales;

-- Generate a Report that shows all key metrics of the business

Select
'Total Sales' as measure_name,
sum(sales_amount) as measure_value
from goldfact_sales
Union all
Select
'Total Quantity' as measure_name,
sum(quantity) as measure_value
from goldfact_sales
union all
Select
'Average Price' as measure_name,
avg(price) as measure_value
from goldfact_sales
union all
Select
'Total Orders' as measure_name,
count(order_number) as measure_value
from goldfact_sales
union all
Select
'Total Products' as measure_name,
count(product_id) as measure_value
from golddim_products
union all
Select
'Total Customers' as measure_name,
count(customer_key) as measure_value
from golddim_customers;

-- ----------------------
-- Magnitude Analysis
-- ----------------------

-- Total customers by countries
select
country,
count(customer_key) as Total_customers
from golddim_customers
group by country
order by count(customer_key) desc;

-- Total customers by gender
select
gender,
count(customer_key) as Total_customers
from golddim_customers
group by gender
order by count(customer_key) desc;

-- Total products by category
select
category,
count(product_key) as Total_products
from golddim_products
where category != ""
group by category
order by count(product_key) desc;

-- Average costs in each category
select
category,
avg(cost) as Avg_cost
from golddim_products
where category != ""
group by category
order by avg(cost) desc;

-- Total revenue generated for each category
select
category,
sum(sales_amount) as Total_revenue
from golddim_products as a
inner join goldfact_sales as b
on a.product_key = b.product_key 
where category != ""
group by category
order by sum(sales_amount) desc;

-- Total revenue generated by each customer
select
a.customer_key,
first_name,
last_name,
sum(sales_amount) as Total_revenue
from goldfact_sales as a
inner join golddim_customers as b
on a.customer_key = b.customer_key
group by a.customer_key, first_name, last_name
order by sum(sales_amount) desc;

-- Distibution of sold items accross countries
select
country,
sum(quantity) as Total_sold_items
from goldfact_sales as a
inner join golddim_customers as b
on a.customer_key = b.customer_key
group by country
order by Total_sold_items desc;

-- ----------------------
-- Ranking Analysis
-- ----------------------

-- 5 products that generate the highest revenue
select
product_name,
sum(sales_amount) as Total_revenue
from goldfact_sales as a
inner join golddim_products as b
on a.product_key = b.product_key
group by product_name
order by sum(sales_amount) desc
limit 5;

-- 5 worst-perfomring products in terms of sale
select
product_name,
sum(sales_amount) as Total_revenue
from goldfact_sales as a
inner join golddim_products as b
on a.product_key = b.product_key
group by product_name
order by sum(sales_amount) asc
limit 5;


